// Contains sample data for API calls, which can be used instead of making the actual API call

export const goingEventsSampleData = [
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-02T03:59:56.212Z",
    date: "6/1/2021",
    description: "Let's clean our coasts!",
    endTime: "1:00PM",
    eventId: "gRM9GtogtDH8eaZieBgy",
    fish: "clownfish",
    goingCount: 2,
    interestedCount: 0,
    location: "Alki Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG100",
    zipCode: 98144,
  },
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "4/8/2021",
    description: "Let's clean our coasts!",
    endTime: "1:00PM",
    eventId: "7aimNkZQELqu9gEdwy1m",
    fish: "clownfish",
    goingCount: 1,
    interestedCount: 0,
    location: "Alki Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
];
