// Contains sample data for API calls, which can be used instead of making the actual API call

// TODO : check for interestedCount field.

export const bannerEventSampleData = [
  {
    id: 0,
    title: "Alki Beach Park Cleanup",
    date: "March 21, 2021",
    goingCount: 15,
    interestedCount: 10,
    descr:
      "Event Description.....Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];

export const goingEventsSampleData = [
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "5/25/2021",
    description: "Let's clean our coasts!1",
    endTime: "1:00PM",
    fish: "clownfish",
    goingCount: 3,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/restore-uw.appspot.com/o/no-img.png?alt=media",
    interestedCount: 8,
    location: "Alki Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
  {
    city: "Bellevue",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "7/3/2021",
    description: "Let's clean our coasts!2",
    endTime: "1:00PM",
    fish: "jellyFish",
    goingCount: 1,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/restore-uw.appspot.com/o/no-img.png?alt=media",
    interestedCount: 0,
    location: "Alki Beach",
    name: "Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
  null,
  {
    city: "Sample City",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "6/15/2021",
    description: "Let's clean our coasts!3",
    endTime: "1:00PM",
    fish: "Starfish",
    goingCount: 1,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/restore-uw.appspot.com/o/no-img.png?alt=media",
    interestedCount: 0,
    location: "Sample Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
  {
    city: "Vancouver",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "6/20/2021",
    description: "Let's clean our coasts!4",
    endTime: "1:00PM",
    fish: "clownfish",
    goingCount: 1,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/restore-uw.appspot.com/o/no-img.png?alt=media",
    interestedCount: 0,
    location: "Vancouver Beach",
    name: "Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "6/22/2021",
    description: "Let's clean our coasts!5",
    endTime: "1:00PM",
    fish: "clownfish",
    goingCount: 1,
    imageUrl:
      "https://firebasestorage.googleapis.com/v0/b/restore-uw.appspot.com/o/no-img.png?alt=media",
    interestedCount: 0,
    location: "Alki Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
];

export const upcomingEventsSampleData = [
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-02T03:59:56.212Z",
    date: "6/1/2021",
    description: "Let's clean our coasts!",
    endTime: "1:00PM",
    eventId: "gRM9GtogtDH8eaZieBgy",
    fish: "clownfish",
    goingCount: 12,
    interestedCount: 10,
    location: "Alki Beach",
    name: "Plastic Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG100",
    zipCode: 98144,
  },
  {
    city: "Seattle",
    commentCount: 0,
    contactNumber: "(206)601-0607",
    createdAt: "2021-03-01T01:18:18.380Z",
    date: "4/8/2021",
    description: "Let's clean our coasts!",
    endTime: "1:00PM",
    eventId: "7aimNkZQELqu9gEdwy1m",
    fish: "clownfish",
    goingCount: 8,
    interestedCount: 7,
    location: "Alki Beach",
    name: "Coastal Cleanup Event",
    organizerName: "Fish Student Association",
    startTime: "10:00AM",
    state: "WA",
    userHandle: "ThomasHandleIMG13",
    zipCode: 98144,
  },
];

export const SampleFriends = [
  "Chris Yee",
  "Thomas Luk",
  "Hannah Shin",
  "Tanduro",
  "David Kim",
  "Lisa Lee",
  "Jay Park",
];
export const SampleFriendRequests = ["Jin Son", "Harry Potter", "Bubble Tea"];
